[[project]]
title = "Data Mining Projects"
category = "Artificial Intelligence"
image = "https://i.imgur.com/ANDVQ4o.png"
url = "https://github.com/Amirbehnam1009/Data-Mining-Projects"

[[project]]
title = "Heart Disease Detector"
category = "Artificial Intelligence"
image = "https://imgur.com/2nNXhDN.png"
url = "https://github.com/Amirbehnam1009/Heart-Disease-Detector-System"

[[project]]
title = "NeuroEvolution Game"
category = "Artificial Intelligence"
image = "https://imgur.com/7110Lj1.png"
url = "https://github.com/Amirbehnam1009/NeuroEvolution-Game"

[[project]]
title = "Persian Search Engine"
category = "Artificial Intelligence"
image = "https://imgur.com/t5T5Ixa.png"
url = "https://github.com/Amirbehnam1009/Information-Retrieval-Search-Engine"

[[project]]
title = "CIFAR10 Image Classification"
category = "Artificial Intelligence"
image = "https://imgur.com/kyHrBGk.png"
url = "https://github.com/Amirbehnam1009/CIFAR10-Image-Classification"

[[project]]
title = "Noise Cancellation and Bitmap Image Compressor"
category = "Other"
image = "./config/assets/projects/project-1.jpg"
url = "https://github.com/Amirbehnam1009/Linear-Algebra-Projects"

[[project]]
title = "Pacman"
category = "Artificial Intelligence"
image = "./config/assets/projects/project-2.png"
url = "https://github.com/Amirbehnam1009/Pacman"